In [93]:
import pandas as pd
import csv
import nltk
import numpy as np
import string
import re

In [94]:
stopwords = ["across", "after", "afterwards", "almost", "alone", "along", "also" "among", "amongst", "amoungst", "another", "anyhow", "anyway", "anywhere", "around", "back", "became","become","becomes", "becoming", "besides", "beyond", "call", "co", "con", "could", "de", "describe", "detail", "due", "eg", "eight", "eleven","else", "elsewhere", "etc", "even", "ever", "every", "everyone",  "everywhere", "fifteen", "fify", "fill", "find", "fire", "first", "five", "former", "formerly", "forty", "found", "four", "front", "full", "get", "give", "go", "hence", "hereafter", "hereby", "herein", "hereupon", "herself", "however", "hundred", "ie", "inc", "indeed", "interest", "itself", "keep", "last", "latter", "latterly", "ltd", "made", "many", "may", "meanwhile", "might", "mill", "mine", "more", "moreover", "most", "mostly", "move", "much", "must", "name", "namely", "nine", "one", "onto", "others", "otherwise", "part", "perhaps", "put", "rather", "see", "seem", "seemed", "seeming", "seems", "serious", "several", "she", "show", "side", "since", "sincere", "six", "sixty", "some", "somehow", "someone", "something", "sometime", "sometimes", "somewhere", "system", "take", "ten", "the", "thence", "thereafter", "thereby", "therefore", "therein", "thereupon", "thickv", "third", "though", "three", "throughout", "thru", "thus", "together", "toward", "towards", "twelve", "twenty", "two", "until", "upon", "us", "via", "whatever", "whence", "whenever", "whereafter", "whereas", "whereby", "wherein", "whereupon", "wherever", "whether", "whither", "whoever", "whose", "why", "with", "within", "would", "he", "his", "she", "her", "hers", "herself", "them", "their", "theirs", "themselves", "what", "which", "who", "whom", "this", "that", "these", "those", "am", "is", "are", "was", "were", "be", "been", "being", "have", "has", "had", "having", "do", "does", "did", "doing", "a", "an", "the", "and", "if", "or", "because", "as", "while", "of", "at", "by", "for", "about", "between", "into", "through", "during", "to", "from", "in", "further", "then", "once", "here", "there", "when", "where", "how", "all", "both", "each", "few", "other", "such", "own", "same", "than", "s", "can", "will", "just", "should", "now", "d", "ll", "m", "o", "re", "ve", "y", "ma"]

In [95]:
chunkDataframe = pd.read_csv("/home/infoobjects/Downloads/final_tagged_dataset (1).csv",header=0, chunksize=1000)

In [96]:
def remove_punctuation(sentence):
  """
  This function is used to remove punctuation from datafram
  @param datafram
  @return datafram
  """
 
  # table = string.maketrans("","")
  # return s.translate(table, string.punctuation.replace("'",""))
  return re.sub(r"[^\w\d'\s]+", "", sentence)


In [97]:
df = pd.DataFrame()
list_dataframe = []
TEXT = "text"
SENTIMENT ="sentiment"
PROBABILITY ="pr"
LABEL = 'label'
dataframe = pd.concat(chunkDataframe, ignore_index=True)
dataframe = dataframe.dropna(subset=["text"], how='all')
dropna_df = dataframe.dropna(subset=[SENTIMENT], how='all')
dataframe[TEXT] = dataframe[TEXT].apply(remove_punctuation)
dropna_df[TEXT] = dropna_df[TEXT].apply(lambda x : ' '.join([item for item in str.split(x.lower()) if item not in stopwords]))
list_dataframe.append(dropna_df)

In [98]:
type(dropna_df)


pandas.core.frame.DataFrame

In [99]:
df = pd.concat(list_dataframe)

In [100]:
df

text sentiment  \
0      u test updated apps on platforms u want tell u...  negative   
1      calling placing my order they told me it 30 mi...  negative   
2           advertisement inversely proportional service  negative   
3      i felt like i eating poor man's chinese ground...  negative   
4      n haven't opened app weeks but it's highest ap...  negative   
5                       service 4.5 on 5 very very fast.  positive   
6      seriously they not think we wouldn't notice ho...  negative   
7      unfortunately long lines festival we can't con...  negative   
8                service, staff not operative all. . . .  negative   
9      i fast food establishment that's exactly i'm l...  negative   
10     we told cancel everything but steak tacos our ...  negative   
11                              none outlets pleased me.  negative   
12                                slowest service world.  negative   
13     it so difficult good private restaurants stay ...  negative   
14     we up 1215 morning birthday bouncer won't let ...  negative   
15     so furious slow service is, joke place employe...  negative   
16                   staff took too long come up my food  negative   
17                   course, you wait queue on busy day.  negative   
18              cherry tomatoes taste pretty bad heated.  negative   
19                                   i can't place star.  negative   
20     i actually yell not acceptable they not serve ...  negative   
21     now, i live india years now, i know rats sacre...  negative   
22     my mind literally blown lmfaoi told him it tab...  negative   
23     place quite empty servers not very active enth...  negative   
24                delievery very slow it took half hour.  negative   
25                            we appetizer but it burnt.  negative   
26                      i glad restaurant gets makeover.  negative   
27     only thing disappointed me unavailability juic...  negative   
28     person i speak tells me different, but honesty...  negative   
29     aspect earns no stars very strong recommendati...  negative   
...                                                  ...       ...   
12118  came on friday night little before 10 couple f...   neutral   
12119                            off i reservation yelp.   neutral   
12120  we arrived half hour early they seated without...   neutral   
12121                   miso soup wakame salad chirashi.   neutral   
12122     what's up izakayas ramen shops popped up city!   neutral   
12123                  ?my wife i tried 5 izakaya's town   neutral   
12124                     we drank water before we out!!   neutral   
12125                                   we went group 5.   neutral   
12126                   we 6 pm reservation on saturday.   neutral   
12127  7.40 (when they served dessert) they handed ch...   neutral   
12128  apparently reservation time limit 90 minutes i...   neutral   
12129                          i big party over weekend.   neutral   
12130                        we got private tatami room.   neutral   
12131                  !that me night today izakaya kou.   neutral   
12132  we tried bacon wrapped mushroom spicy tuna rol...   neutral   
12133                                  it's cheese corn.   neutral   
12134  we ordered lot starting appetizer grilled sash...   neutral   
12135                   i arrived restaurant very empty.   neutral   
12136  i didn't really understand restaurant empty so...   neutral   
12137  my yelp review i glad i place i want write about!   neutral   
12138  i always pass area finally decided try my friend.   neutral   
12139                                    we tried dishes   neutral   
12140                   nice redesign but food mediocre.   neutral   
12141                                       it wed-night   neutral   
12142            they reservations on open table though.   neutral   
12143                         we didn't try sushi rolls.   neu

In [101]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.cross_validation import StratifiedKFold, cross_val_score, train_test_split
datas=df
msg_train, msg_test, label_train, label_test = train_test_split(datas[TEXT], datas[SENTIMENT], test_size=0.2)

In [102]:
msg_train

927               noodles bit bland taste less vegetables.
10568    they awesome outdoor seating area great enjoy ...
11697                                        prices great!
4875                           they not try solve problem.
8809      very tiny place but food worth wait on busy day.
7560                        food amazing...an experience."
3503     terrible attitude- shame food not bad, rude se...
3296                                 they gave quesadilla.
8473                                        food terrific!
8095     fresh baked italian bread great they offer var...
299      wth no recipes all. page ads! can't believe hi...
7202     great place your goal guzzle beer you your lun...
107      they don't know behave, talk , satisfied custo...
9622       its always so nice clean staff nice not stupid.
4155                                             it awful.
1492     place packed til closing local sheriffs came c...
6129                              curd rice i imagined i

In [103]:
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import MultinomialNB
from sklearn.grid_search import GridSearchCV
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer, TfidfVectorizer
from sklearn.metrics import classification_report, f1_score, accuracy_score, confusion_matrix
from sklearn.cross_validation import StratifiedKFold, cross_val_score, train_test_split

overall_sentiment_nb_detector =None
import gzip
import pickle as cPickle
pipeline = Pipeline([('bow', CountVectorizer(ngram_range=(1, 3), max_features = 30000)), ('tfidf', TfidfTransformer()), ('classifier', MultinomialNB())])
  # pipeline parameters to automatically explore and tune
params = {
    'tfidf__use_idf': (True, False),
    'classifier__alpha': (1, 0.1, 0.01, 0.001, 0.0001, 0.00001),
    'tfidf__sublinear_tf': (True, False),
}
grid = GridSearchCV(
pipeline,
params, # parameters to tune via cross validation
refit=True, # fit using all data, on the best detected classifier
n_jobs=-1,
scoring='accuracy',
cv=StratifiedKFold(label_train, n_folds=5),
)
# train
nb_detector = grid.fit(msg_train, label_train)
predictions = nb_detector.predict(msg_test)
print(":: Confusion Matrix")

print(confusion_matrix(label_test, predictions))

print(":: Classification Report")
print(classification_report(label_test, predictions))
filepath = ('/home/infoobjects/Desktop/text-anal/multinomial_nb.pkl.gz')
# save model to pickle file
import os.path
filepath = ('/home/infoobjects/Desktop/text-anal/multinomial_nb.pkl.gz')
if os.path.exists(filepath):
    print("model already exists")
    pass
else:
    
    with gzip.GzipFile(filepath, 'wb') as fout:
        cPickle.dump(nb_detector, fout)
    print('model written to: ' +  filepath)


:: Confusion Matrix
[[ 881    6  125]
 [ 113   37   84]
 [  41    7 1136]]
:: Classification Report
             precision    recall  f1-score   support

   negative       0.85      0.87      0.86      1012
    neutral       0.74      0.16      0.26       234
   positive       0.84      0.96      0.90      1184

avg / total       0.84      0.85      0.82      2430

model already exists


In [104]:
def predict(message, model_detect):
  """
  This function is used for predict the review category based on training model. 
  @param review
  @paran model_object 
  @return predicted category with probability  
  """

  # calculate predicted category for given message
  nb_predict = model_detect.predict([message])[0]
  # calculate probabilty for predicted category for given message
  nb_perc = max(model_detect.predict_proba([message])[0])
  return {PROBABILITY : round(nb_perc,5), LABEL : nb_predict }

In [105]:
import traceback

def classify_overall_sentiment(sentence) :
    global overall_sentiment_nb_detector
    global stopwords
    """
    This function is used classify the sentiment  
    @param sentence
    @return sentiment
    """
    sentence = ' '.join([word for word in sentence.split() if word not in stopwords])
    non_alphanumeric_cleaning = remove_punctuation(sentence)
    try:
        filepath = ('/home/infoobjects/Desktop/text-anal/multinomial_nb.pkl.gz')
        overall_sentiment_nb_detector = cPickle.load(gzip.open(filepath,'rb'))
        return predict(sentence, overall_sentiment_nb_detector)
    except Exception as e:
     print(traceback.format_exc())

In [109]:
sentence_input = input()
sentiment_data = classify_overall_sentiment(sentence_input)
print(" ")
print("output ==> ",sentiment_data)

I came here with a friend for happy hour around 4:00 or 5:00 on a weekday. The place was totally empty, so I chose a booth seat towards the back, though there's also bar seating for those that are interested. There was only one guy working there at the time (since there was a manageable crowd of one) and he took my drink order. I asked about which red wines were part of happy hour, and he said there was only one. How strange! Okay.  My friend eventually arrived and ordered the same sole happy hour red wine. We also got cheese and charcuterie platters to share. Those were tasty, and I would totally return just to have them again! The only downside is that we were in a rush to leave, and the place soon got busy after everyone else got off work, and the restaurant was suddenly understaffed with two people.  We had a challenge of getting the check, to the point where I had to get out of my seat to hunt down the waitress who was busy running around and was laser focused on her next task. I'